export const SEARCH = "SEARCH";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
export const ON_SEARCH_ERROR = "ON_SEARCH_ERROR";
export const UPDATE_LOADING_STATE = "UPDATE_LOADING_STATE";